#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source "${ZDOTDIR:-$HOME}/.zenv"

# weatherme keys in .env
alias wm="weatherme -d |  column -s '|' -t"
alias wmnow="weatherme"


# virtualenv wrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh

alias sleep="pmset sleepnow"
alias fucking="sudo"

# for git
eval "$(hub alias -s)"


alias tailf="tailf -f"


export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/heroku/bin:/Users/avaleske/Library/Haskell/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/texbin"

